-- Devices table for Ovelo v1 (Device-based licensing)

create table if not exists public.devices (
  id uuid primary key default gen_random_uuid(),

  -- hashed / stable machine fingerprint, generated by the app
  machine_fingerprint text not null,

  -- platform info
  platform text not null,           -- 'mac' | 'windows' | 'linux'
  initial_version text not null,    -- app version at registration
  current_version text not null,    -- last seen app version

  license_status text not null default 'free',  -- 'free' | 'pro'

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),

  constraint devices_machine_unique unique (machine_fingerprint)
);

create index if not exists devices_last_seen_at_idx on public.devices (last_seen_at);
